<?php

use Illuminate\Database\Seeder;

class ContainerTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $containerTypes = [
            ['isocode' => '10G1', 'dimension'=> "10' x 8' x 8'", 'description'=>"10' Dry Container"],
            ['isocode' => '20B0', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Bulk"],
            ['isocode' => '20B1', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Bulk"],
            ['isocode' => '20B3', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Bulk"],
            ['isocode' => '20B4', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Bulk"],
            ['isocode' => '20B5', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Bulk"],
            ['isocode' => '20B6', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Bulk"],
            ['isocode' => '20G0', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '20G1', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '20G2', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '20G3', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '20H0', 'dimension'=>"20' x 8' x 8'", 'description'=>"20' Insulated"],
            ['isocode' => '20H1', 'dimension'=>"20' x 8' x 8'", 'description'=>"20' Insulated"],
            ['isocode' => '20H2', 'dimension'=>"20' x 8' x 8'", 'description'=>"20' Insulated"],
            ['isocode' => '20H5', 'dimension'=>"20' x 8' x 8'", 'description'=>"20' Insulated"],
            ['isocode' => '20H6', 'dimension'=>"20' x 8' x 8'", 'description'=>"20' Insulated "],
            ['isocode' => '20P1', 'dimension'=>"20' x 8' x 8'", 'description'=>"20' Flat"],


            ['isocode' => '20P2', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Flat"],
            ['isocode' => '20P3', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Flat Collapsible"],
            ['isocode' => '20P4', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Flat Collapsible "],
            ['isocode' => '20P5', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Platform Superstructure"],
            ['isocode' => '20R0', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '20R1', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '20R2', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '20R3', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '20R8', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '20R9', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '20T0', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' TANK CONTAINER"],
            ['isocode' => '20T1', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' TANK CONTAINER"],
            ['isocode' => '20T2', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' TANK CONTAINER"],
            ['isocode' => '20T3', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Tank for Dangerous Liquid"],
            ['isocode' => '20T4', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Tank for Dangerous Liquid"],
            ['isocode' => '20T5', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Tank for Dangerous Liquid "],
            ['isocode' => '20T6', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Tank for Dangerous Liquid "],
            ['isocode' => '20T7', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Tank for Gas"],
            ['isocode' => '20T8', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Tank for Gas"],
            ['isocode' => '20T9', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Tank for Gas"],
            ['isocode' => '20U0', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '20U1', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '20U2', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '20U3', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '20U4', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '20U5', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '20V0', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Ventilated"],
            ['isocode' => '20V2', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Ventilated"],
            ['isocode' => '20V4', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Ventilated"],
            ['isocode' => '21P1', 'dimension'=> "20' x 8' x 8'", 'description'=>"20' Flat(Fixed ends)"],

            ['isocode' => '22B0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Bulk, Non-pressurized, hopper type, closed"],
            ['isocode' => '22B1', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Bulk, Non-pressurized, hopper type, airtight"],
            ['isocode' => '22B3', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Bulk, Pressurized, horizontal discharge, test pressure 150 kPa"],
            ['isocode' => '22B4', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Bulk, Pressurized, horizontal discharge, test pressure 265 kPa"],
            ['isocode' => '22B5', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Bulk, Pressurized, tipping discharge, test pressure 150 kPa"],
            ['isocode' => '22B6', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Bulk, Pressurized, tipping discharge, test pressure 265 Kpa"],
            ['isocode' => '22G0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Box, Non-vented"],
            ['isocode' => '22G1', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Box, Passive Vents"],
            ['isocode' => '22G2', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '22G3', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '22G4', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '22G8', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '22G9', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' GENERAL PURPOSE CONTAINER"],
            ['isocode' => '22H0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Insulated"],
            ['isocode' => '22H2', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Insulated "],
            ['isocode' => '22P0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Flat"],
            ['isocode' => '22P1', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Flat"],
            ['isocode' => '22P2', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Flat"],
            ['isocode' => '22P3', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Flat Collapsible "],
            ['isocode' => '22P4', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Flat, Collapsible Posts"],
            ['isocode' => '22P5', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Platform Superstructure"],
            ['isocode' => '22P7', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Platform"],
            ['isocode' => '22P8', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Platform"],
            ['isocode' => '22P9', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' FLAT (COLLAPSIBLE)"],
            ['isocode' => '22R0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '22R1', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '22R2', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Box, Refrigerated, self powered"],
            ['isocode' => '22R3', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Box, Refrigerated & Heated, self powered"],
            ['isocode' => '22R7', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Reefer "],
            ['isocode' => '22R9', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Reefer"],
            ['isocode' => '22S1', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' NAMED CARGO CONTAINER"],
            ['isocode' => '22T0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank"],
            ['isocode' => '22T1', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank "],
            ['isocode' => '22T2', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank "],
            ['isocode' => '22T3', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank for Dangerous Liquid"],
            ['isocode' => '22T4', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank for Dangerous Liquid "],
            ['isocode' => '22T5', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank for Dangerous Liquid "],
            ['isocode' => '22T6', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank for Dangerous Liquid"],
            ['isocode' => '22T7', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank for Gas"],
            ['isocode' => '22T8', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Tank for Gas"],
            ['isocode' => '22U0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '22U1', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '22U6', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Hard Top"],
            ['isocode' => '22V0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' Box, Ventilated"],
            ['isocode' => '22V2', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' VENTILATED CONTAINER"],
            ['isocode' => '22V3', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' VENTILATED CONTAINER"],
            ['isocode' => '25G0', 'dimension'=> "20' x 9'6'' x 8'", 'description'=>"20' GP-CONTAINER OVER-HEIGHT"],
            ['isocode' => '25R1', 'dimension'=> "20' x 9'6'' x 8'", 'description'=>"20' High Cube Reefer "],
            ['isocode' => '25U1', 'dimension'=> "20' x 9'6'' x 8'", 'description'=>"20' High Cube Open Top Container"],
            ['isocode' => '26G0', 'dimension'=> "20' x 8'6'' x 8'", 'description'=>"20' GP-CONTAINER OVER-HEIGHT"],
            ['isocode' => '26H0', 'dimension'=> "20' x 9'6'' x 8'", 'description'=>"20' High Cube Insulated "],
            ['isocode' => '26T0', 'dimension'=> "20' x 9'6'' x 8'", 'description'=>"20' High Cube Tank "],
            ['isocode' => '28P0', 'dimension'=> "20' x 4'3'' x 8'", 'description'=>"20' Platform"],
            ['isocode' => '28T8', 'dimension'=> "20' x 4'3'' x 8'", 'description'=>"20' Tank for Gas "],
            ['isocode' => '28U1', 'dimension'=> "20' x 4'3'' x 8'", 'description'=>"20' Open Top"],
            ['isocode' => '28V0', 'dimension'=> "20' x 4'3'' x 8'", 'description'=>"20' VE-HALF-HEIGHT =1448 MM HEIGHT"],
            ['isocode' => '29P0', 'dimension'=> "", 'description'=>"20' PLATFORM"],//107 Dimension was empty

            ['isocode' => '2EG0', 'dimension'=> "20' x 9'6'' x 8'/8'2''", 'description'=>"20' High Cube Dry Container"],
            ['isocode' => '42B0', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' DRY BULK CONTAINER"],
            ['isocode' => '42G0', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Box, Non-vented"],
            ['isocode' => '42G1', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Box, Passive Vents"],
            ['isocode' => '42G9', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Hanger Container"],
            ['isocode' => '42H0', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Insulated  "],
            ['isocode' => '42P0', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Flat"],
            ['isocode' => '42P1', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Flat, Solid Fixed Ends"],
            ['isocode' => '42P2', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Flat, Fixed Posts"],
            ['isocode' => '42P3', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Flat, Collapsible Solid Ends"],
            ['isocode' => '42P4', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Flat, Collapsible Posts"],
            ['isocode' => '42P5', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' OPEN SIDED COTAINER"],
            ['isocode' => '42P6', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' FLAT SPACE SAVER"],
            ['isocode' => '42P8', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Platform"],
            ['isocode' => '42P9', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Platform "],
            ['isocode' => '42R0', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Reefer"],
            ['isocode' => '42R1', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Reefer "],
            ['isocode' => '42R2', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Box, Refrigerated, self powered"],
            ['isocode' => '42R3', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Reefer "],
            ['isocode' => '42R9', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Reefer"],
            ['isocode' => '42S1', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Automobile Container"],
            ['isocode' => '42T2', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Tank"],
            ['isocode' => '42T5', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Tank for Dangerous Liquid "],
            ['isocode' => '42T6', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Tank for Dangerous Liquid"],
            ['isocode' => '42T8', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Tank for Gas  "],
            ['isocode' => '42U1', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Open Top "],
            ['isocode' => '42U6', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Hard Top "],
            ['isocode' => '42V0', 'dimension'=> "40' x 8'6'' x 8'", 'description'=>"40' Ventilated "],
            ['isocode' => '45B3', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' BULK CONTAINER"],
            ['isocode' => '45G0', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' Box (high cube) GP, Non-vented"],
            ['isocode' => '45G1', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' Box (high cube) GP, Vented"],
            ['isocode' => '45P3', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"45P3 High Cube Flat Collapsible (40' x 9'6'' x 8') "],
            ['isocode' => '45P8', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"45P8 High Cube Platform (40' x 9'6'' x 8') "],
            ['isocode' => '45R0', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' Box, Refrigerated, needs external power"],
            ['isocode' => '45R1', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' High Cube Reefer "],
            ['isocode' => '45R2', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' Box, Refrigerated, self powered"],
            ['isocode' => '45R3', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' Box, Refrigerated & Heated, self powered"],
            ['isocode' => '45R9', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' High Cube Reefer"],
            ['isocode' => '45U1', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' High Cube Open Top"],
            ['isocode' => '45U6', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' High Cube Hard Top"],
            ['isocode' => '46H0', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' High Cube Insulated "],
            ['isocode' => '46P3', 'dimension'=> "40' x 9'6'' x 8'", 'description'=>"40' High Cube Flat Collapsible "],
            ['isocode' => '48P0', 'dimension'=> "40' x 4'3'' x 8'", 'description'=>"40' Platform"],
            ['isocode' => '48T8', 'dimension'=> "40' x 4'3'' x 8'", 'description'=>"40' Tank for Gas"],
            ['isocode' => '48U1', 'dimension'=> "40' x 4'3'' x 8'", 'description'=>"40' Open Top"],
            ['isocode' => '49P0', 'dimension'=> "40' x 4'3'' x 8'", 'description'=>"40' Platform"],
            ['isocode' => '4CG0', 'dimension'=> "40' x 8'6'' x 8'/8'2''", 'description'=>"40' Geneal Purpose Container"],
            ['isocode' => 'L0G1', 'dimension'=> "45' x 8' x 8'", 'description'=>"45' High Cube General Purpose, Vented"],
            ['isocode' => 'L2G1', 'dimension'=> "45' x 8'6'' x 8'", 'description'=>"45' High Cube General Purpose, Unvented"],
            ['isocode' => 'L5G0', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' Box (high cube), Non-vented"],
            ['isocode' => 'L5G1', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' Box (high cube), Vented"],
            ['isocode' => 'L5R0', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' High Cube Reefer"],
            ['isocode' => 'L5R1', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' High Cube Reefer"],
            ['isocode' => 'L5R2', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' High Cube Reefer"],
            ['isocode' => 'L5R3', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' High Cube Reefer"],
            ['isocode' => 'L5R4', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' High Cube Reefer"],
            ['isocode' => 'L5R8', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' High Cube Reefer"],
            ['isocode' => 'L5R9', 'dimension'=> "45' x 9'6'' x 8'", 'description'=>"45' High Cube Reefer"],
            ['isocode' => 'LDG1', 'dimension'=> "45' x 9' x 8'/8'2''", 'description'=>"45' High Cube General Purpose"],
            ['isocode' => 'LDG8', 'dimension'=> "45' x 9' x 8'/8'2''", 'description'=>"45' High Cube General Purpose"],
            ['isocode' => 'LEG1', 'dimension'=> "45' x 9'6'' x 8'/8'2''", 'description'=>"45' High Cube Dry "],
            ['isocode' => 'LEG8', 'dimension'=> "45' x 9'6'' x 8'/8'2''", 'description'=>"45' High Cube General Purpose "],
            ['isocode' => 'LEG9', 'dimension'=> "45' x 9'6'' x 8'/8'2''", 'description'=>"45' High Cube General Purpose "],
            ['isocode' => 'LLG1', 'dimension'=> "45' x 8'6'' x >8'2''", 'description'=>"45' General Purpose "],
            ['isocode' => 'LNG1', 'dimension'=> "45' x 9'6'' x >8'2''", 'description'=>"45' High Cube General Purpose "],
            ['isocode' => 'LNR1', 'dimension'=> "45' x 9'6'' x >8'2''", 'description'=>"45' High Cube Reefer "],
            ['isocode' => 'MNG1', 'dimension'=> "48' x 9'6'' x 8' ", 'description'=>"48' Box (high cube), 102\" Wide, Vented"],
            ['isocode' => 'MPG1', 'dimension'=> "48' x 9'6'' x 8' ", 'description'=>"48' Box (high cube), 102\" Wide, Vented"],
        ];

        foreach($containerTypes as $containerType){
            \App\Containertype::create($containerType);
        }
    }
}
